### PR TITLE
dashboard dir fix

### PR DESCRIPTION
**Pull request by Odianosen25**

### CODE REVIEW

**Comment by tjbradley** [comment]
So I’m not familiar with github structure or getting help. I’m having the issue where it fails to init. Dir_dashboard. I know you commented about the fix in the next release but I don’t quite understand how the pull request works and how to fix it

**Comment by ReneTode** [comment]
@tjbradley just upgrade appdaemon from appdaemon 4.0.0 to 4.0.1

**Comment by Aneurin** [comment]
This didn't quite make it into 4.0.1. If you want this fix without applying the changes yourself, you'll have to use dev or wait for 4.0.2.

**Comment by ReneTode** [comment]
another solution is just add the http section to appdaemon.yaml

**Comment by fastrax** [comment]
@ReneTode I am currently using Appdaemon in Docker which was upgraded to 4.0.0 by Watchtower. I believe that this fix I am looking for. Specifically, what would I need to add to my yaml to get back up and running again? Thanks for any assistance.

**Comment by jshank** [comment]
@fastrax  - Change your docker-compose or docker command line file to use `image: "acockburn/appdaemon:dev"`. Remember to revert back to image: `"acockburn/appdaemon"` when the fixed release comes out.

**Comment by junior466** [comment]
@ReneTode Care to explain where I would add the http section? I am having this error and it appears to be related:

        2020-02-07 15:36:01.544453 WARNING hello_world: ------------------------------------------------------------
        2020-02-07 15:40:22.701952 WARNING hello_world: ------------------------------------------------------------
        2020-02-07 15:40:22.702072 WARNING hello_world: Unexpected error initializing app: hello_world:
        2020-02-07 15:40:22.702159 WARNING hello_world: ------------------------------------------------------------
        2020-02-07 15:40:22.702713 WARNING hello_world: Traceback (most recent call last):
          File "/usr/local/lib/python3.6/dist-packages/appdaemon/app_management.py", line 820, in check_app_updates
            await self.init_object(app)
          File "/usr/local/lib/python3.6/dist-packages/appdaemon/app_management.py", line 280, in init_object
            self.AD, name, self.AD.logging, app_args, self.AD.config, self.app_config, self.AD.global_vars
          File "/usr/local/lib/python3.6/dist-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
            adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
          File "/usr/local/lib/python3.6/dist-packages/appdaemon/adbase.py", line 75, in __init__
            self.dashboard_dir = self.AD.http.dashboard_dir
        AttributeError: 'NoneType' object has no attribute 'dashboard_dir'

        2020-02-07 15:40:22.702829 WARNING hello_world: ------------------------------------------------------------

My config:

        logs:
          main_log:
            filename: /home/user/haappdaemon/conf/logs/appdaemon.log
          access_log:
            filename: /home/user/haappdaemon/conf/logs/access.log
          error_log:
            filename: /home/user/haappdaemon/conf/logs/error.log
        appdaemon:
          disable_apps: 1
          latitude: REDACTED
          longitude: REDACTED
          elevation: REDACTED
          time_zone: REDACTED
          # threads: 10
          plugins:
            HASS:
              type: hass
              ha_url: http://192.168.143.11:8123
              token: REDACTED
          dash_url: http://192.168.143.11:8124

**Comment by ReneTode** [comment]
@fastrax sorry that i missed your question.
hope you got it working again.

**Comment by tjbradley** [comment]
Sorry for the late response. No I never did get it working on 4.0.1 I just reinstalled 3.0.5 to fix that. My real issues is actually with pigpio daemon on a Raspbian system. Trying to use AppDaemon to be the handler between home assistant and remote application(aquarium light) where AppDaemon is installed. communication back and fourth is great it’s the interacting with the GPIOs that’s a issue. Currently trying to use AppDaemon to initialize shell commands via subprocess and pipe the commands through the terminal to the other pigpio daemon

**Comment by fastrax** [comment]
Hi Team, I still haven't been able to get back up and running.
The :dev version didn't seem to fix things. 
Specifically, what http info would I need to add to my yaml to get back up and running again?

I am still getting the following error.log:

`2020-02-18 18:30:58.886294 WARNING hello_world: ------------------------------------------------------------
2020-02-18 18:30:58.886608 WARNING hello_world: Unexpected error initializing app: hello_world:
2020-02-18 18:30:58.886852 WARNING hello_world: ------------------------------------------------------------
2020-02-18 18:30:58.892119 WARNING hello_world: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/local/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'

2020-02-18 18:30:58.892402 WARNING hello_world: ------------------------------------------------------------`

Any help would be hugely appreciated.

**Comment by Odianosen25** [comment]
@fastrax,

Looking at the log, I am certain you are not using the latest dev fix, as the line where that fix is wrong in your log. kindly try and download latest and let us know how it goes.

But not willing to do that, simply follow the docs [here](https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#configuring-the-http-component) to add the http component.

Regards

**Comment by ThaSiouL** [comment]
This fix is not in 4.0.3. It's neither in the master branch, nor the 4.0.3 tag. The only merged file was the history commit.

**Comment by ThaSiouL** [comment]
This fix is not in 4.0.3. It's neither in the master branch, nor the 4.0.3 tag. I checked the files from the zip download and it's not in there either. I got the same line numbers as fastrax above.

The only commit merged into stable was the history file commit.

**Comment by fastrax** [comment]
I have never been able to get it back up and running. :(

**Comment by ReneTode** [comment]
@fastrax all you need to do is change your appdaemon.yaml

make sure you have the following parts as root sections:

```
api:
admin:
hadashboard:
http:
  url: http://... # the url you had as dashboard url before you updated (in most cases ha ip:5050)
```
if you got hassio, then look at the addon github for more info

**Comment by foxcris** [comment]
Is this fix really in the latest 4.0.3 release? Seems like @Odianosen25 is right. I still have this error and cannot get appdaemon 4 running.
````
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/local/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/local/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
