### ISSUE TITLE
ImportError: cannot import name 'create_connection'

### ISSUE THREAD

**Issue by uchagani** [home-assistant/appdaemon#226]
I'm getting a ```ImportError: cannot import name 'create_connection'``` error.  I have ```websocket-client``` installed.  AppDaemon works fine with version 2.1.12 but I was trying to advantage of the ```exclude_dirs``` options in v3

AppDaemon Version: appdaemon 3.0.0b1

HA Version: 0.61.1

OS: Raspbian GNU/Linux 9 (stretch)

Stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/admain.py", line 335, in main
    admain.main()
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/admain.py", line 331, in main
    self.run(appdaemon, hadashboard)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/admain.py", line 58, in run
    self.AD = ad.AppDaemon(self.logger, self.error, loop, **appdaemon)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 240, in __init__
    mod = __import__(full_module_name, globals(), locals(), [module_name], 0)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/plugins/hass/hassplugin.py", line 5, in <module>
    from websocket import create_connection
ImportError: cannot import name 'create_connection'
```

pip3 list:

```
websocket (0.2.1)
websocket-client (0.44.0)
```

**Comment by acockburn** [comment]
Thanks for the thorough bug report - this works OK for me on Ubuntu with identical versions, and I also have reports of it working ok on PI - the requirements haven;t changed since 2.1.12. Have you used a different VENV or otherwise changed the environment?

**Comment by uchagani** [comment]
it's odd.  When I installed appdaemon inside of my Home Assistant venv it works.  but globally it doesn't.

**Comment by acockburn** [comment]
That points to a difference in the 2 envs then, I assume you checked the versions of websocket and the client in the global?

**Comment by uchagani** [comment]
Correct. Both are the same. Any downside to running appdaemon in the same
venv as home assistant?

**Comment by acockburn** [comment]
No they can run fine together - the only potential issue is that HASS requires specific versions of packages whereas appdaemon only asks for minimum versions. Sometimes an AD install can install a too recent version of a package and hass barfs - if that happens you can manually downgrade and AD will be fine with it - it shouldn't happen often but I've seen folks do it a couple of times. FWIW, I run HASS in an venv and AppDaemon globally, so they don;t fight, but I don;t have a venv specifically for AD.

**Comment by uchagani** [comment]
hmm ok then i'll create a virtual env just for appdaemon
