### ISSUE TITLE
AppDaemon won't start after upgrade

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/appdaemon#30]
I upgraded appdaemon to 1.5 and got the following error when trying to start it

```
● appdaemon.service - LSB: Start daemon at boot time
   Loaded: loaded (/etc/init.d/appdaemon)
   Active: failed (Result: exit-code) since Sun 2017-01-29 10:47:19 CST; 1min 45s ago
  Process: 24611 ExecStop=/etc/init.d/appdaemon stop (code=exited, status=0/SUCCESS)
  Process: 24696 ExecStart=/etc/init.d/appdaemon start (code=exited, status=1/FAILURE)

Jan 29 10:47:19 hass appdaemon[24696]: File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
Jan 29 10:47:19 hass appdaemon[24696]: return ep.load()
Jan 29 10:47:19 hass appdaemon[24696]: File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2291, in load
Jan 29 10:47:19 hass appdaemon[24696]: return self.resolve()
Jan 29 10:47:19 hass appdaemon[24696]: File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
Jan 29 10:47:19 hass appdaemon[24696]: module = __import__(self.module_name, fromlist=['__name__'], level=0)
Jan 29 10:47:19 hass appdaemon[24696]: ImportError: No module named 'appdaemon.appdaemon'
Jan 29 10:47:19 hass systemd[1]: appdaemon.service: control process exited, code=exited status=1
Jan 29 10:47:19 hass systemd[1]: Failed to start LSB: Start daemon at boot time.
Jan 29 10:47:19 hass systemd[1]: Unit appdaemon.service entered failed state.

```

I have not upgraded to the latest HA, still on 0.36.1

**Comment by acockburn** [comment]
Seems like the install failed for some reason. Can you run it from the command line?

I would suggest a manual pip uninstall and re-install. Let me know if it works.

**Comment by turboc1208** [comment]
I did the pip uninstall and re-install, that didn't help.  Then I did a pip uninstall and deleted the appdaemon directory under the hass user.  I then did an install of appdaemon, copied my appdaemon.cfg file back from last nights backup and if I specify where the cfg file is, it will start, but now I get the following errors on everything that tries to start.
```

2017-01-29 14:41:53.087500 WARNING ------------------------------------------------------------
2017-01-29 14:41:54.156731 WARNING ------------------------------------------------------------
2017-01-29 14:41:54.157996 WARNING Unexpected error during loading of calalarm:
2017-01-29 14:41:54.158658 WARNING ------------------------------------------------------------
2017-01-29 14:41:54.159657 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 730, in readApp
    init_object(name, class_name, module_name, config[name])
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 516, in init_object
    conf.objects[name]["object"].initialize()
  File "/home/hass/code/appdaemon/calalarm/calalarm.py", line 82, in initialize
    self.schedulealarm(room)
  File "/home/hass/code/appdaemon/calalarm/calalarm.py", line 196, in schedulealarm
    self.addalarm(room,m)
  File "/home/hass/code/appdaemon/calalarm/calalarm.py", line 137, in addalarm
    self.log("Adding alarm")
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appapi.py", line 57, in log
    msg = self._sub_stack(msg)
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appapi.py", line 40, in _sub_stack
    msg = msg.replace("__module__", stack[2].filename)
AttributeError: 'tuple' object has no attribute 'filename'

2017-01-29 14:41:54.160226 WARNING ------------------------------------------------------------
2017-01-29 14:41:54.268588 WARNING ------------------------------------------------------------
2017-01-29 14:41:54.269175 WARNING Unexpected error during loading of speak:
2017-01-29 14:41:54.269596 WARNING ------------------------------------------------------------
2017-01-29 14:41:54.270506 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 730, in readApp
    init_object(name, class_name, module_name, config[name])
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 516, in init_object
    conf.objects[name]["object"].initialize()
  File "/home/hass/code/appdaemon/speak/speak.py", line 44, in initialize
    self.log("using device {} for my voice".format(self.device))
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appapi.py", line 57, in log
    msg = self._sub_stack(msg)
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appapi.py", line 40, in _sub_stack
    msg = msg.replace("__module__", stack[2].filename)
AttributeError: 'tuple' object has no attribute 'filename'
```

Appdaemon is installed under the hass user's home directory.  That is to say the appdaemon cfg path is

/home/hass/appdaemon/conf/appdaemon.cfg

**Comment by turboc1208** [comment]
Found it.  stack is not a dictionary, it's a list so you have to specify the element in the list, and you were looking at the first level 1 which was always log since you added a second function to do the replace.  You needed to go back 2 levels to get to the correct data.  The below seems to work.

  def _sub_stack(self, msg):
    stack = inspect.stack()
    msg = msg.replace("__module__", stack[2][1])
    msg = msg.replace("__line__", str(stack[2][2]))
    msg = msg.replace("__function__", stack[2][3])
    return(msg)

**Comment by acockburn** [comment]
I'll take a look but it worked fine when I tested it - what version of python are you using? I think this changed at some point in the recent past.

**Comment by turboc1208** [comment]
pi@hass:~ $ python3 -V
Python 3.4.2

**Comment by turboc1208** [comment]
latest RPI patches and no difference, still blows up.

**Comment by acockburn** [comment]
Released 1.5.1 to temporarily disable this functionality so it will at least start. I'll revisit when I have some more time.

**Comment by acockburn** [comment]
Functionality restored in 1.5.2 and it shouldn't break anything this time. Your variation works in 3.5 as well as 3.4 so I adopted it - thanks! Also, as an abundance of caution, I recoded it so that if there is an issue with earlier versions of Python, it will break only of the substitution strings are actually used meaning people can fix any potential issue by not using the feature rather than it breaking for everyone.
