### ISSUE TITLE
Apps fail to load on >= 3.0.2 - get_hass_config AttributeError

### ISSUE THREAD

**Issue by jantman** [home-assistant/appdaemon#581]
I've been running AppDaemon 3.0.1 for about a year now, installed in a py3.5 virtualenv via pip. I just tried upgrading to 3.0.5 and a bunch of my apps failed to load, throwing a traceback for:

```
AttributeError: 'ZwaveChecker' object has no attribute 'get_hass_config'
```

All of my apps and config (except secrets) are public, at: https://github.com/jantman/home-automation-configs/tree/master/appdaemon

The one thing that may be a clue here is that the apps that failed to load (a) have multiple inheritance, and (b) call ``self.get_hass_config()`` in their ``initialize()`` method.

After experiencing this issue when I upgraded to 3.0.5, I then downgraded in order to 3.0.4, 3.0.3, 3.0.2, and back to 3.0.1. Once I got back to 3.0.1, everything is working properly as it used to.

I can't find anything in the release notes or HISTORY relating to the ``get_hass_config()`` method and I see it still present in the source, so I'm not sure what the cause is...

**Comment by ReneTode** [comment]
get_hass_config() changed to get_plugin_config("hass"), but its somehow lost to mention that in the docs.
its already taken care of in the dev docs. but docs are only updated when a new release is there.

**Comment by jantman** [comment]
Ok, thanks so much for the info! Would it be possible to get this added to the changelog / release notes from the relevant release?

**Comment by jantman** [comment]
For anyone who happens to find this issue... on 3.0.5 at least, it's ``self.get_plugin_config()`` not ``self.get_plugin_config("hass")``

**Comment by ReneTode** [comment]
its actually
self.get_plugin_config(namespace = "the name from your namespace")
i used hass because my namespace for the hass plugin is hass
it defaults to the namespace that is set before the command

@Odianosen25 would you please add to the changelog that get_hass_config() has been changed to get_plugin_config() as a breaking change from 3.0.2

**Comment by Odianosen25** [comment]
This change wasn't supposed to enter the stable release if I am not wrong. But will do as requested

**Comment by ReneTode** [comment]
i know, get_hass_config() should have stayed, and i am not sure, but i think Andrew restored it in dev.
but in the end its still broken in 3.0.5, so its better recorded as breaking change and when we go to AD 4 (and its restored) then add a remark that its added as repair.

over time i have had several questions about it, now its documented ;)

**Comment by Odianosen25** [comment]
The breaking change has been noted. Will be closing this issue now if everyone is happy?

@jantman, please reopen is not satisfied with what has been done.

Regards
