### ISSUE TITLE
Error after upgrading HA to 0.84.2 from 0.83

### ISSUE THREAD

**Issue by JZ-SmartThings** [home-assistant/appdaemon#449]
Had everything working great in older version of HA 0.83.x but upgraded to latest 0.84.2 last night. That upgrade of HA broke AppDaemon dashboards. All devices now show **entity not found** error. I also see the following in the HA logs every few seconds for each device. When I turn off the Docker container hosting AppDaemon, the errors in HA logs stop.

```
Log Details (ERROR)
Sat Dec 15 2018 09:47:05 GMT-0800 (Pacific Standard Time)
Error handling message: {'id': 6, 'type': 'subscribe_events'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/websocket_api/connection.py", line 66, in async_handle
    handler(self.hass, self, schema(msg))
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/websocket_api/commands.py", line 102, in handle_subscribe_events
    if not connection.user.is_admin:
AttributeError: 'NoneType' object has no attribute 'is_admin'
```

I did try updating AppDaemon to the latest last night and today a few minutes ago (because I saw some recent commits) but the error still persists and AD seems sadly broken. Here's the command I used to build the Docker image just in case:

`git clone https://github.com/home-assistant/appdaemon.git; docker image build appdaemon --tag acockburn/appdaemon; sudo docker run -d --name=appdaemon --restart always -it -p 5050:5050 -v /home/hass/appdaemon:/conf acockburn/appdaemon:latest`

I'm of course using the legacy auth which worked well but seems as though HA is not adding the is_admin attribute to that legacy login. Not sure if the new HA auth is yet available in AD but I have successfully used legacy auth for a while so it looks to be a recent change in HA that broke that compatibility.

Thank you!!!

**Comment by acockburn** [comment]
AD has had new auth since 3.0.2 via long lived tokens and this is the supported way to do it now. I'll give 84.2 a spin with the new auth and if that is OK I'll close this issue. I think we have seen previously that 0.84 broke legacy auth anyway. Here is a link to setting up the new auth:

https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html?highlight=long%20lived#hass-authentication

**Comment by acockburn** [comment]
Yup, it's fine with 0.84.2. Please upgrade to long lived tokens and you should be good.
