### ISSUE TITLE
Cannot start AppDaemon

### ISSUE THREAD

**Issue by psamim** [home-assistant/appdaemon#533]
Hi,
I recently installed `AppDaemon` in a venv using pip. I created the `appdaemon.yml` file. When starting the `appdaemon` I get the following and it seems that it does not read the apps. I created the test app but nothing happens. I also get the following warnings.

```
$ appdeamon -c conf

/home/samim/workspace/AppDaemon/venv/lib/python3.7/site-packages/appdaemon/admain.py:184: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated
, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(config_file_contents)
/home/samim/workspace/AppDaemon/venv/lib/python3.7/site-packages/appdaemon/admain.py:213: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated
, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(config_file_contents)
2019-03-21 15:34:21.561759 INFO AppDaemon Version 3.0.2 starting
2019-03-21 15:34:21.561981 INFO Configuration read from: conf/appdaemon.yaml
```

I am using Archlinux with Python 3.7.2
This is the content of my `conf/appdaemon.yaml`:
```
appdaemon:
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: XXX
      token: XXX 

```
Thanks

**Comment by acockburn** [comment]
Did you create an apps.yaml file in the apps directory?

The error looks like just a warning and I would expect it to still work so it may be another issue.

**Comment by psamim** [comment]
@acockburn Thanks for fast reply! This is the files I have:
```
$ tree conf

conf
├── appdaemon.yaml
└── apps
    ├── apps.yaml
    └── hello.py

1 directory, 3 files
```

```
$ cat conf/apps/apps.yaml

hello_world:
  module: hello
  class: HelloWorld
```
```
$ cat conf/apps/hello.py

import appdaemon.plugins.hass.hassapi as hass

class HelloWorld(hass.Hass):

  def initialize(self):
     self.log("Hello from AppDaemon")
     self.log("You are now ready to run Apps!")
```

I also run `appdeamon` with debug flag:
```
$   appdaemon -c conf -D DEBUG
2019-03-21 19:59:27.917395 INFO AppDaemon Version 3.0.2 starting
2019-03-21 19:59:27.917572 INFO Configuration read from: conf/appdaemon.yaml
2019-03-21 19:59:27.917660 DEBUG AppDaemon Section: None
2019-03-21 19:59:27.917738 DEBUG HADashboard Section: None
```

Will I see some errors if the config values are incorrect? Or some required values are missing?

Because even with only below two lines of config I get the same results:

```
appdaemon:
    threads: 10
```

**Comment by Odianosen25** [comment]
Hello @psamim,

First you using python 3.7, and AD states 3.6 max. PyYaml has been updated to 5.1 which I think you are using, and AD has not been upgraded to use it.

Please uninstall PyYaml and run `pip3 install PyYAML==3.13`

Kind regards

**Comment by psamim** [comment]
@Odianosen25 Hi,

I installed python 3.6.8 and pyYAML 3.13 but still get the same results.

```
(venv36) $ which appdaemon
/home/samim/workspace/AppDaemon/venv36/bin/appdaemon

(venv36) $ python --version
Python 3.6.8

(venv36) $ which python
/home/samim/workspace/AppDaemon/venv36/bin/python
```

**Comment by psamim** [comment]
```

**Comment by Odianosen25** [comment]
Can you pls show the output of pip3 freeze?

**Comment by psamim** [comment]
Sure.

```
(venv36) $ pip freeze
aiohttp==2.3.10
aiohttp-jinja2==0.15.0
appdaemon==3.0.2
astral==1.10.1
async-timeout==3.0.1
bcrypt==3.1.6
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
daemonize==2.5.0
feedparser==5.2.1
idna==2.8
idna-ssl==1.1.0
iso8601==0.1.12
Jinja2==2.10
MarkupSafe==1.1.1
multidict==4.5.2
paho-mqtt==1.4.0
pycparser==2.19
pytz==2018.9
PyYAML==3.13
requests==2.21.0
six==1.12.0
sseclient==0.0.23
urllib3==1.24.1
voluptuous==0.11.5
websocket-client==0.56.0
yarl==1.1.0

(venv36)  $ which pip
/home/samim/workspace/AppDaemon/venv36/bin/pip
```

**Comment by psamim** [comment]
I do not get the warnings regarding yaml but still no info showing the apps are running or no errors.

```
(venv36) $ appdaemon -c conf -D DEBUG
2019-03-21 21:24:18.602350 INFO AppDaemon Version 3.0.2 starting
2019-03-21 21:24:18.602539 INFO Configuration read from: conf/appdaemon.yaml
2019-03-21 21:24:18.602608 DEBUG AppDaemon Section: None
2019-03-21 21:24:18.602663 DEBUG HADashboard Section: None
```

**Comment by psamim** [comment]
Can this be related? When I hit ctrl-c to stop the appdaemon I get these:
```
2019-03-21 21:24:18.602350 INFO AppDaemon Version 3.0.2 starting
2019-03-21 21:24:18.602539 INFO Configuration read from: conf/appdaemon.yaml
2019-03-21 21:24:18.602608 DEBUG AppDaemon Section: None
2019-03-21 21:24:18.602663 DEBUG HADashboard Section: None
o
^C2019-03-21 21:26:02.423048 INFO Keyboard interrupt
Traceback (most recent call last):
  File "/home/samim/.pyenv/versions/3.6.8/lib/python3.6/posixpath.py", line 193, in ismount
    s1 = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samim/workspace/AppDaemon/venv36/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/home/samim/workspace/AppDaemon/venv36/lib/python3.6/site-packages/appdaemon/admain.py", line 394, in main
    admain.main()
  File "/home/samim/workspace/AppDaemon/venv36/lib/python3.6/site-packages/appdaemon/admain.py", line 379, in main
    utils.check_path("config_file", self.logger, config_file_yaml, pathtype="file")
  File "/home/samim/workspace/AppDaemon/venv36/lib/python3.6/site-packages/appdaemon/utils.py", line 182, in check_path
    while not os.path.ismount(dir):
  File "/home/samim/.pyenv/versions/3.6.8/lib/python3.6/posixpath.py", line 193, in ismount
    s1 = os.lstat(path)
  File "/home/samim/workspace/AppDaemon/venv36/lib/python3.6/site-packages/appdaemon/admain.py", line 53, in handle_sig
    self.stop()
  File "/home/samim/workspace/AppDaemon/venv36/lib/python3.6/site-packages/appdaemon/admain.py", line 59, in stop
    self.AD.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
```

**Comment by Odianosen25** [comment]
Can you kindly paste your entire appdaemon.yaml file?

**Comment by Odianosen25** [comment]
And pls paste the full directory path of your configuration folder

**Comment by psamim** [comment]
I fixed the issue but it seems really weird!

 If I give the config path (`-c` argument) as relative path, it does not work. If I give full path it works. With full path it works in both Python 3.6 and 3.7.

Full path:
```
(venv36)  $ appdaemon -c /home/samim/workspace/AppDaemon/conf
2019-03-21 21:35:41.164379 INFO AppDaemon Version 3.0.2 starting
2019-03-21 21:35:41.164596 INFO Configuration read from: /home/samim/workspace/AppDaemon/conf/appdaemon.yaml
2019-03-21 21:35:41.166198 INFO AppDaemon: Starting Apps
2019-03-21 21:35:41.169379 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2019-03-21 21:35:41.221263 INFO AppDaemon: HASS: HASS Plugin Initializing
2019-03-21 21:35:41.222076 INFO AppDaemon: HASS: HASS Plugin initialization complete
2019-03-21 21:35:41.222585 INFO Dashboards are disabled
2019-03-21 21:35:41.222707 INFO API is disabled
2019-03-21 21:35:42.840881 INFO AppDaemon: HASS: Connected to Home Assistant 0.89.2
```

Relative path: (stuck here)
```
(venv36)  $ appdaemon -c ./conf
2019-03-21 21:34:26.234027 INFO AppDaemon Version 3.0.2 starting
2019-03-21 21:34:26.234242 INFO Configuration read from: ./conf/appdaemon.yaml
```

**Comment by psamim** [comment]
I checked the docs and I saw the word `full path` was mentioned in the help text in the command line but it was not mentioned in the description below it in the online docs. So it seems it was my fault that I missed it. But if this is so important let's make it more clear and emphasized because It seems you missed it too. ;)

 Thanks for quick replies and great work.

Regards

**Comment by Odianosen25** [comment]
Hello @psamim,

Glad it was fixed. I was beginning to suspect it, that was why I requested your full path after the `PyYaml` didn't fix it.

But all good anyways.

Kindly close issue since its fixed now.

Kind regards

**Comment by psamim** [comment]
The actual issue is that in the log messages it was said that the config was successfully read without errors (`INFO Configuration read from: ./conf/appdaemon.yaml`) but actually it was not read at all and had errors silently. So I think this needs a fix.

Thanks

**Comment by Odianosen25** [comment]
@psamim you have a good point.

@acockburn do you think based on this, this issue should be left opened?

Regards

**Comment by acockburn** [comment]
I reopened it - we should fix this as it has cropped up before.

**Comment by acockburn** [comment]
Fixed in dev

**Comment by callagga** [comment]
I've just hit this installing HA & AD (been a while for me since I've used HA).  I have " AppDaemon Version 4.0.1".

Is the next update far off?  (re next day or so) Or otherwise which work around would you advise to get "unstuck"?

**Comment by callagga** [comment]
just noted in another thread starting up the new admin interface is a work around, and this worked for now.  i.e. adding this to the appdaemon config file:

http:
    url: http://<<your ip>>:5050

admin:

**Comment by bmcgair** [comment]
Trying to upgrade to the 4.0.3 docker image. All apps break with messages like:
```
2020-03-08 11:20:41.115068 WARNING AppDaemon: Unable to find module laundry - initialize() skipped
2020-03-08 11:20:41.115259 WARNING AppDaemon: Unable to find module shop - initialize() skipped
```
Is this related? conf dir mounted on /conf in the image. apps dir with apps.yaml and my apps within /conf. Tried with both app_dir: /conf/apps set or unset. Doesn't matter, can't find my modules.
